[workspace]
members = [
  "crates/*",
  "examples/rust/rust-client",
]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
mrhc_core = { path = "crates/mrhc_core" }
mrhc_matrix_adapter = { path = "crates/mrhc_matrix_adapter" }
mrhc_proto = { path = "crates/mrhc_proto" }

prost = "0.14"
prost-build = "0.14"
interprocess = { version = "2.2", default-features = false, features = ["tokio"] }
bytes = "1.10"

tokio = { version = "1.48.0", default-features = false, features = [
  "rt-multi-thread",
  "io-std",
  "io-util",
  "macros",
  "sync",
] }
async-trait = "0.1"

url = "2.5.7"
matrix-sdk = { version = "0.16.0", features = [
  "sso-login"
] }
matrix-sdk-base = { version = "0.16.0", default-features = false }
matrix-sdk-crypto = { version = "0.16.0", default-features = false }

aes-gcm = "0.10"
argon2 = "0.5"

serde = "1.0"
serde_json = "1.0"

log = "0.4"
log4rs = "1.4"
