[package]
name = "gouda_matrix"
version = "0.6.0"
edition = "2021"
publish = false

[dependencies]
gouda_core = { git = "https://github.com/gonicus/gouda-core-rs.git", rev = "5174b58264412950585a0bfa8d8ff51b2ed6be0e" }
gouda_proto = { git = "https://github.com/gonicus/gouda-core-rs.git", rev = "5174b58264412950585a0bfa8d8ff51b2ed6be0e" }

prost = "0.14"
interprocess = { version = "2.2", default-features = false, features = ["tokio"] }
clap = { version = "4.6", features = ["derive"] }

tokio = { version = "1.48", default-features = false, features = [
  "rt-multi-thread",
  "io-std",
  "io-util",
  "macros",
  "sync",
  "time",
] }
tokio-stream = "0.1"
futures-util = "0.3"
async-trait = "0.1"

url = "2.5.7"

js_int = "0.2.2"
matrix-sdk = { version = "0.18.0", features = [
  "sso-login", "markdown", "bundled-sqlite"
] }
matrix-sdk-crypto = { version = "0.18.0", default-features = false }
ruma-common = "0.19"

mime = "0.3"
mime_guess = "2.0"

aes-gcm = "0.10"
argon2 = "0.5"

serde = "1.0"
serde_json = "1.0"

log = "0.4"
log4rs = "1.4"

infer = "0.19"

thiserror = "2.0"

[build-dependencies]
vergen = { version = "10.0", features = ["build", "cargo", "rustc"] }

[dev-dependencies]
tempdir = "0.3"
test-log = "0.2"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
todo = "deny"
unimplemented = "deny"
