[package]
name = "mrhc_matrix_adapter"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
mrhc_proto.workspace = true
mrhc_core.workspace = true

prost.workspace = true

tokio.workspace = true
async-trait.workspace = true

js_int.workspace = true
matrix-sdk.workspace = true
matrix-sdk-base.workspace = true
matrix-sdk-common.workspace = true
matrix-sdk-crypto.workspace = true
ruma-common.workspace = true
url.workspace = true
mime.workspace = true
mime_guess.workspace = true

aes-gcm.workspace = true
argon2.workspace = true

serde.workspace = true
serde_json.workspace = true

log.workspace = true

futures-util.workspace = true
infer.workspace = true

thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
tempdir.workspace = true
test-log.workspace = true
