sequenceDiagram
    actor User

    participant App
    Note right of App: Gonnect

    participant Client
    Note right of Client: matrix-rust-headless-client

    participant SDK
    Note right of SDK: matrix-sdk

    App ->> Client: Check if Secret Storage is setup
    Client ->> App: Secret Storage status

    opt Secret Storage not setup
        App -> Client: TODO: Secret Storage setup
    end

    App ->> Client: Check if our device is signed
    Client ->> App: Device signing status
    App ->> User: Notify User about signing status

    opt Device is not signed
        App ->> Client: Request available verification methods (Secret Storage, CrossSigning)
        Client -> SDK: TODO: Check if cross signing or secret storage is available.
        Client ->> App: Available verification methods
        App ->> User: Available verification methods
        User ->> App: Desired verification method

        alt Verification with Secret Storage key
            User ->> App: Secret Storage key
            App ->> Client: Secret Storage Key
            Client -> SDK: TODO
        else Verification using Cross Signing
            App -> Client: TODO: Bootstrap cross signing

            Client ->> SDK: Request own device verification with our supported methods
            SDK -->> Client: Notify when a device accepts the request with the agreed cross signing methods
            Client ->> App: Agreed cross signing methods
            App ->> User: Display available cross signing methods

            alt Our device selects a cross signing method
                User ->> App: Selected cross signing method
                App ->> Client: Selected cross signing method
                Client ->> SDK: Selected cross signing method
            else Second device selects a cross signing method
                SDK -->> Client: Selected cross signing method
                Client ->> App: Selected cross signing method
                App ->> User: Display selected cross signing method
            end

            alt Verification with SAS
                SDK ->> Client: The emojis both devices have agreed on
                Client ->> App: The emojis to confirm
                App ->> User: The emojis to confirm
                User ->> App: Confirmation of the emojis
                App ->> Client: Confirmation of the emojis
                Client ->> SDK: Confirmation of the emojis
                SDK -->> Client: Other device confirmed emojis as well
                Client ->> App: Verification successful
                App ->> User: Verification successful
            else Verification with QR
                SDK -> Client: TODO
            end
        end
    end
