on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Rust

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust:
    name: Check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install nightly rustfmt
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --all --all-targets --all-features -- -D warnings

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Test
        run: cargo test --all --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Machete
        uses: bnjbvr/cargo-machete@main

      - name: Typos
        uses: crate-ci/typos@master
